/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'saer6003' at '1/24/17 10:08 AM' with Gradle 3.0
 *
 * @author saer6003, @date 1/24/17 10:08 AM
 */
public class Library {
	
	public static void main(String[] args) {
		System.out.println("hola desde gradle");
	}
	
	
    public boolean someLibraryMethod() {
        return true;
    }
}
